### ISSUE TITLE
Will keep update iOS FMMR?

### ISSUE THREAD

**Issue by devinlai** [wseemann/FFmpegMediaMetadataRetriever-iOS#1]
Hi There,

Will FMMR-iOS version be update?

I try to use this library in my project,

But it have some issue about memory leak, 

and cannot download video thumbnail. (Work well on image file)

Is it possibile to fix these issue?

Thanks,

**Comment by wseemann** [comment]
I just updated the library per your request. Please consider donating to the project: https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=2BDTFVEW9LFZY
